### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Fuckingnameless** [sasha0552/nvidia-pstate#1]
i just installed this via pip and getting this error:

nvidia-pstate set-pstate -ps 0
**libnvidia-api.so: cannot open shared object file: No such file or directory**
usage: nvidia-pstate [-h] [-i ID [ID ...]] [-ps PERF_STATE] [-q] [-s] [-v]
**nvidia-pstate: error: unrecognized arguments: set-pstate**

**Comment by sasha0552** [comment]
Hi. I updated cli today to make it more similar to `nvidia-smi`. Updated the readme to make it match the actual cli.

Use
```
nvidia-pstate -ps 0
```
to set performance state.

You can also explore the parameters with the --help options.
```
nvidia-pstate --help
```

About this error
>  libnvidia-api.so: cannot open shared object file: No such file or directory

Make sure you have the nvidia driver and driver utilities installed.
The `nvidia-utils` package for ArchLinux. The library may have a different name in other distributions. What distribution are you using? I'll try to reproduce it.

**Comment by sasha0552** [comment]
I think you are using Debian or its derivatives. Should be fixed now, try updating the package.
Make sure you have the required package installed:
https://github.com/sasha0552/nvidia-pstate?tab=readme-ov-file#linux
(I'm sure only about Arch and Debian packages, on Debian derivatives just use `apt search libnvidia-api.so.1` to get the name of the package you need).
Thanks for reporting.

**Comment by sasha0552** [comment]
Can you post output of `nvidia-smi -q -d SUPPORTED_CLOCKS`?
The performance state is actually a memory clock, so if you have more than one, it should work with P100. Although the performance state may not be 0 but 1, for example.
The one with only one (and low) graphics clock is usually PState 8.

For P40:
```
GPU 00000000:00:00.0
    Supported Clocks
 !      Memory                            : 3615 MHz      <-- pstate 0
            Graphics                      : 1531 MHz
            ...
            Graphics                      : 544 MHz
 !      Memory                            : 405 MHz       <-- pstate 8
            Graphics                      : 544 MHz
```
