### ISSUE TITLE
More info regarding NvAPI_GPU_SetForcePstate parameters

### ISSUE THREAD

**Issue by maz-net-au** [sasha0552/nvidia-pstate#4]
I had a chat to someone today about what the parameters are for this function.

**hPhysicalGpu**: ctypes.c_void_p - gpu handle
**pstate**: int - Desired p-state. Valid values are 0 - 15 where 0 is the highest performance and 15 is idle. Not all cards support all states. By setting it to 16 you're using the fallback state as described below.
**int3**: int - The fallback state. 1 = fallback to high perf, 2 = fallback to low perf. This allows the driver to control the p-state as needed with the default being high or low performance based on the value passed. Using 2 means that the gpu will attempt to use a low p-state unless higher performance is required, and then it automatically increases as needed.

Hope that's helpful to you.

**Comment by sasha0552** [comment]
Thank you very much for this information. Added as docstring to the function.
